from . import models_data
from . import base
from . import relatives_extra_information
from . import t_register
from . import third_staff
from . import right_holders
from . import reports_t_registro
from . import reports_third_staff
from . import reports_right_holders
